### PR TITLE
Added xorg-libx11 in conda

### LINKED ISSUE #55: CI fails on Ubuntu/conda with "Could NOT find X11 (missing: X11_X11_INCLUDE_PATH)"
Related run: https://github.com/ami-iit/yarp-device-openxrheadset/actions/runs/12248271881/job/34177782082

### PR DESCRIPTION
**Pull request by S-Dafarra**
Fixes #55

### CODE REVIEW

**Comment by traversaro** [comment]
Thanks! Probably there was some change upstream in conda-forge w.r.t. to this. Indeed, this is also why the latest conda package build failed in https://github.com/robotology/robotology-superbuild/actions/runs/12246902843 :

~~~
2024-12-10T01:06:13.5710895Z [3/8] Building CXX object _deps/glfont-build/CMakeFiles/GLFont.dir/src/GLFont.cpp.o
2024-12-10T01:06:13.5711345Z FAILED: _deps/glfont-build/CMakeFiles/GLFont.dir/src/GLFont.cpp.o 
2024-12-10T01:06:13.5714420Z $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++ -DGLFont_DEFAULT_FONTS_PATH=\"$SRC_DIR/build/_deps/glfont-src/fonts\" -DGLFont_EXPORTS -I$SRC_DIR/build/_deps/glfont-src/include -isystem $PREFIX/include/freetype2 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/yarp-device-openxrheadset-0.0.5 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -O3 -DNDEBUG -fPIC -MD -MT _deps/glfont-build/CMakeFiles/GLFont.dir/src/GLFont.cpp.o -MF _deps/glfont-build/CMakeFiles/GLFont.dir/src/GLFont.cpp.o.d -o _deps/glfont-build/CMakeFiles/GLFont.dir/src/GLFont.cpp.o -c $SRC_DIR/build/_deps/glfont-src/src/GLFont.cpp
2024-12-10T01:06:13.5717895Z In file included from $BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr/include/GL/glx.h:30,
2024-12-10T01:06:13.5718469Z                  from $SRC_DIR/build/_deps/glfont-src/include/GLFont/GLConfig.h:12,
2024-12-10T01:06:13.5719210Z                  from $SRC_DIR/build/_deps/glfont-src/include/GLFont/GLFont.h:4,
2024-12-10T01:06:13.5719595Z                  from $SRC_DIR/build/_deps/glfont-src/src/GLFont.cpp:1:
2024-12-10T01:06:13.5720001Z $PREFIX/include/X11/Xlib.h:44:10: fatal error: X11/X.h: No such file or directory
2024-12-10T01:06:13.5720449Z    44 | #include <X11/X.h>
2024-12-10T01:06:13.5720772Z       |          ^~~~~~~~~
2024-12-10T01:06:13.5721088Z compilation terminated.
2024-12-10T01:06:13.5721491Z [4/8] Building CXX object _deps/glfont-build/CMakeFiles/GLFont.dir/src/FTLabel.cpp.o
2024-12-10T01:06:13.5722025Z FAILED: _deps/glfont-build/CMakeFiles/GLFont.dir/src/FTLabel.cpp.o 
2024-12-10T01:06:13.5722516Z   File "/home/runner/miniconda3/envs/test/bin/conda-mambabuild", line 10, in <module>
2024-12-10T01:06:13.5722892Z     sys.exit(main())
2024-12-10T01:06:13.5723072Z              ^^^^^^
2024-12-10T01:06:13.5723483Z   File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/boa/cli/mambabuild.py", line 301, in main
2024-12-10T01:06:13.5723959Z     call_conda_build(action, config)
2024-12-10T01:06:13.5724472Z   File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/boa/cli/mambabuild.py", line 273, in call_conda_build
2024-12-10T01:06:13.5724986Z     result = api.build(
2024-12-10T01:06:13.5725172Z              ^^^^^^^^^^
2024-12-10T01:06:13.5725575Z   File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/conda_build/api.py", line 250, in build
2024-12-10T01:06:13.5726032Z     return build_tree(
2024-12-10T01:06:13.5726218Z            ^^^^^^^^^^^
2024-12-10T01:06:13.5726668Z   File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/conda_build/build.py", line 3638, in build_tree
2024-12-10T01:06:13.5727168Z     packages_from_this = build(
2024-12-10T01:06:13.5727438Z                          ^^^^^^
2024-12-10T01:06:13.5727893Z   File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/conda_build/build.py", line 2506, in build
2024-12-10T01:06:13.5728366Z     utils.check_call_env(
2024-12-10T01:06:13.5728952Z   File "/home/runner/miniconda3/envs/test/lib/python3.12/site-packages/conda_build/utils.py", line 405, in check_call_env
2024-12-10T01:06:13.5729556Z     return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
2024-12-10T01:06:13.5732413Z $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++ -DGLFont_DEFAULT_FONTS_PATH=\"$SRC_DIR/build/_deps/glfont-src/fonts\" -DGLFont_EXPORTS -I$SRC_DIR/build/_deps/glfont-src/include -isystem $PREFIX/include/freetype2 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/yarp-device-openxrheadset-0.0.5 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -O3 -DNDEBUG -fPIC -MD -MT _deps/glfont-build/CMakeFiles/GLFont.dir/src/FTLabel.cpp.o -MF _deps/glfont-build/CMakeFiles/GLFont.dir/src/FTLabel.cpp.o.d -o _deps/glfont-build/CMakeFiles/GLFont.dir/src/FTLabel.cpp.o -c $SRC_DIR/build/_deps/glfont-src/src/FTLabel.cpp
~~~

**Comment by S-Dafarra** [comment]
By checking a [working run](https://github.com/ami-iit/yarp-device-openxrheadset/actions/runs/12227848265/job/34105175717) with a [not working one](https://github.com/ami-iit/yarp-device-openxrheadset/actions/runs/12248271881/job/34177782082), I noticed that ``xorg-xorgproto`` was missing

**Comment by traversaro** [comment]
The situation seems a bit in a flux:
* https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6688
* https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6816
* https://github.com/conda-forge/tk-feedstock/issues/55

Just switching to use `xorg-xorgproto` seems indeed to be correct solution.

**Review by traversaro — APPROVED** [review]

**Comment by S-Dafarra** [comment]
Thanks @traversaro

**Pull request merged**
